# Site settings
title: CFRP
email: hyperstudio-support@mit.edu
description: "Informational website for the Comédie Française Registers Project."
baseurl: ""
url: "http://cfregisters.org"
twitter_username: mithyperstudio
github_username:  hyperstudio

# Build settings
markdown: kramdown
permalink: pretty
