# Site settings
title: CFRP
email: hyperstudio-support@mit.edu
description: "Informational website for the Comédie Française Registers Project."
baseurl: ""
url: "http://cfregisters.org"
twitter_username: mithyperstudio
github_username:  hyperstudio

# Where things are
source:           .
destination:      ./_site

# Handling Reading
exclude:           ["templates", "Gemfile", "Gemfile.lock"]

# Conversion
markdown: kramdown

# Outputting
# permalink: /:categories/:title/ <-- trying to get this to use lang variable
permalink: pretty

defaults:
  -
    scope:
      path: _posts/en
    values:
      layout: _layouts/default
      lang: en
  -
    scope:
      path: _posts/fr
    values:
      layout: _layouts/default
      lang: fr