# Site settings
title: CFRP
email: hyperstudio-support@mit.edu
description: "Informational website for the Comédie Française Registers Project."
# baseurl: ""
url: "http://cfregisters.org"
twitter_username: mithyperstudio
github_username:  hyperstudio

# Where things are
destination:      ./_site
source:           .

# collections:
#   en_news:
#     output: true
#     permalink: /en/news/:name/
#   fr_news:
#     output: true
#     permalink: /fr/news/:name/


# Handling Reading
exclude:           ["templates", "Gemfile", "Gemfile.lock"]

# Conversion
markdown: kramdown

# Outputting
# permalink: /:categories/:title/ <-- trying to get this to use lang variable
permalink: /:categories/:title/

# Using the following approach for multilingual posts:
# http://sylvain.durand.tf/making-jekyll-multilingual/
# I have a question out on whether we can get the lang variable into permalinks
defaults:
  -
    scope:
      path: _posts/en
    values:
      layout: _layouts/page
      lang: en
  -
    scope:
      path: _posts/fr
    values:
      layout: _layouts/page
      lang: fr