# Site settings
title: CFRP
email: hyperstudio-support@mit.edu
description: "Informational website for the Comédie Française Registers Project."
baseurl: ""
url: "http://cfregisters.org"
twitter_username: mithyperstudio
github_username:  hyperstudio

# Where things are
destination:      ./_site
source:           .


# Handling Reading
exclude:           ["templates", "Gemfile", "Gemfile.lock"]

# Conversion
markdown: kramdown

# Outputting
# Note that en and fr need to appear first as categories to establish URLs properly
permalink: /:categories/:title/

# Using the following approach for multilingual posts:
# http://sylvain.durand.tf/making-jekyll-multilingual/
defaults:
  -
    scope:
      path: _posts/news/en
    values:
      layout: _layouts/article
      lang: en
  -
    scope:
      path: _posts/news/fr
    values:
      layout: _layouts/article
      lang: fr