# Site settings
title: CFRP
email: hyperstudio-support@mit.edu
description: "Informational website for the Comédie Française Registers Project."
baseurl: "/cfrp-website"
url: "http://hyperstudio.github.io/cfrp-website"
twitter_username: mithyperstudio
github_username:  hyperstudio

# Build settings
markdown: kramdown
permalink: pretty
