# Site settings
title: CFRP
email: hyperstudio-support@mit.edu
description: "Informational website for the Comédie Française Registers Project."
baseurl: ""
url: "http://cfregisters.org"
twitter_username: mithyperstudio
github_username:  hyperstudio

# Where things are
destination:      ./_site
source:           .


# Handling Reading
exclude:           ["templates", "Gemfile", "Gemfile.lock"]

# Conversion
markdown: kramdown

# Outputting
# Note that en and fr need to appear first as categories to establish URLs properly
permalink: /:categories/:title/

# Using the following approach for multilingual posts:
# http://sylvain.durand.tf/making-jekyll-multilingual/
defaults:
  -
    scope:
      path: "en"
      type: "posts"
    values:
      lang: "en"
      layout: "post"
  -
    # This automatically works for all content in fr path
    scope:
      path: "fr"
      type: "posts"
    values:
      lang: "fr"
      layout: "post"